version: '3.8'

services: 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file: .env
    networks:
      - app_network
    


  tomcat:
    image: tomcat:11.0-jdk17
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./students-web/target/students-web.war:/usr/local/tomcat/webapps/students.war
    depends_on:
      - mongodb
    env_file: .env
    networks:
      - app_network
    

  terminal:
    build: 
      context: ./students-terminal
    container_name: terminal
    env_file: .env
    depends_on:
      - mongodb
    stdin_open: true    
    tty: true
    networks:
      - app_network


volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge